development: &default
  adapter: postgresql
  database: mockapp_development
  encoding: utf8
  host: localhost
  min_messages: warning
  pool: 2
  timeout: 5000
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>

test:
  <<: *default
  database: mockapp_test
